### ISSUE TITLE
Rename `THREAD_COUNT` to `PROCESS_COUNT`

### ISSUE THREAD

**Issue by drujensen** [Amber-Crystal/Amber#100]
> As a developer I would like to read how many Processes are running since Amber::Server is launching new processes, not threads.

https://github.com/Amber-Crystal/Amber/blob/master/src/amber.cr#L46

Acceptance Criteria:
- [x] Variable is renamed from THREAD_COUNT to PROCESS_COUNT

**Comment by eliasjpr** [comment]
https://github.com/Amber-Crystal/Amber/pull/101
