### ISSUE TITLE
Too many open files, crash when serving static files.

### ISSUE THREAD

**Issue by skunkworker** [Amber-Crystal/amber#108]
When running a stress test against the example hello world app I got it to crash when trying to hit `/index.html`

`wrk -d 20 -t 4 -c 1015 http://0.0.0.0:4000/index.html`

```
Params: =index.html
accept: Too many open files (Errno)
0x10defddc5: *CallStack::new:CallStack at ??
0x10df00a6e: *raise<Errno>:NoReturn at ??
0x10dfbb065: *Amber::Server#start:Nil at ??
0x10defbfa2: __crystal_main at ??
0x10df24bdb: main at ??
```

I'm thinking it could be an open file descriptor issue or something else, but I'll look into see if its a crystal-lang bug or something that we can tackle.
Possibly related - https://github.com/crystal-lang/crystal/issues/780

**Comment by skunkworker** [comment]
I may have been running into 10.11's ulimit limit of only 256 open file descriptors.
https://blog.dekstroza.io/ulimit-shenanigans-on-osx-el-capitan/

**Comment by elorest** [comment]
Yeah thats definitely it. With that error. You have to change your ulimit.

**Comment by eliasjpr** [comment]
Is this still a valid issue. It looks like is more a server config issue. LMK

**Comment by akzhan** [comment]
It's invalid. `wrk` ran with 1015 of HTTP connections to keep open with each thread and with 4 threads.

So I suppose that 4K connections may be established sometimes. You need approx. limit of 8K+ of descriptor (4K connections and 4K static files).

https://stackoverflow.com/questions/880557/socket-accept-too-many-open-files

**Comment by drujensen** [comment]
closing this issue.
