### ISSUE TITLE
Support SSL like Kemal.

### ISSUE THREAD

**Issue by faustinoaq** [amber-crystal/amber#151]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem
    * Checked that your issue isn't already filed: https://github.com/Amber-Crystal/amber/issues
    * Checked that there is not already a Crystal Shard that provides the described functionality: http://crystalshards.xyz/

### Description

Currently Amber doesn't support SSL, see [gitter comment](https://gitter.im/Amber-Crystal/Lobby?at=597c8e2476a757f80858cd66)

### Steps to Reproduce

1. Install Amber:CMD
2. Create new Amber project
3. Try to configure SSL on Amber

**Expected behavior:** Amber supporting SSL

**Actual behavior:** Need to use external program like Nginx to use SSL

**Reproduces how often:** 100%

### Versions

0.1.5

### Additional Information

@sdogruyol, the creator of Kemal said:

> it's simple enough
> just pass SSL Context to HTTP::Server

Currently, Kemal does the following:

```
./your_kemal_app --ssl --ssl-key-file your_key_file --ssl-cert-file your_cert_file
```

See: http://kemalcr.com/docs/ssl/

**Comment by eliasjpr** [comment]
Solved with https://github.com/amber-crystal/amber/pull/152
