### ISSUE TITLE
redirect_to and render should be able to halt the execution, even in before_action

### ISSUE THREAD

**Issue by c910335** [amber-crystal/amber#156]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem
    * Checked that your issue isn't already filed: https://github.com/Amber-Crystal/amber/issues
    * Checked that there is not already a Crystal Shard that provides the described functionality: http://crystalshards.xyz/

### Description

If `redirect_to` or `render` is called in `before_action`, the action should not run, but it does run currently.
`redirect_to` or `render` in action is fine since we can simply `return`.
However, if they can cancel the action in `before_action`, `before_action` can be more useful and easy to do lots of things like authentication.

### Steps to Reproduce

1. Start a new Amber project.
2. Generate a scaffold.
3. Add a redirect_to (or render) call in before_action

**Expected behavior:** Action should not run.

**Actual behavior:** Action does run.

**Reproduces how often:** 100%

### Versions

0.1.5

### Additional Information

An example what I want to do

```crystal
class SomethingController < ApplicationController
  before_action do
    all { authenticate_user! }
  end

  private def authenticate_user!
    @current_user ||= if current_user_id = session[:current_user_id]
                        User.find current_user_id
                      else
                        redirect_to "/"
                      end
  end

  def create # or other action
     # This action should not run if user has not signed in yet
  end
end
```

**Comment by eliasjpr** [comment]
@c910335 I saw your issue this morning and you can always write the response to have the redirect take effect immediately, after your redirect you can do 'response.write'. We will consider adding an argument to the redirect_to method 'force: true'

**Comment by c910335** [comment]
@eliasjpr 
No, response.write cannot cancel the action, and even response.close cannot

sample code

```crystal
class TestController < ApplicationController
  before_action do
    all do
      redirect_to("/")
      response.close
    end
  end

  def index
    raise "This action should not run."
    ""
  end
end
```

result

```
Unhandled exception on HTTP::Handler
This action should not run. (Exception)
```

Although the redirect is successful, the action still run.

**Comment by david50407** [comment]
How about raise an Exception and catch it in a Pipeline?
Here's a simple example in Amber itself https://github.com/amber-crystal/amber/blob/master/src/amber/router/pipe/error.cr

**Comment by eliasjpr** [comment]
@david50407 raising an exception have some cost and it is not an error. We are considering adding a `force/halt` argument to the **redirect_to** method and add a circuit breaker to the execution.

**Comment by elorest** [comment]
You can also return render or redirect. I don't think that render should halt an operation but rather just return the expected string value. You can do what you want with it at that point.

**Comment by david50407** [comment]
@elorest return in `before_filter` seems won't write back to Response? [src](https://github.com/amber-crystal/amber/blob/0935dee6637552fda2d80c2bcf6c64194c2e993a/src/amber/dsl/router.cr#L16)

**Comment by elorest** [comment]
Render shouldn't be called in a before filter. Only a redirect. Or perhaps
an exception like devise in rails.

**Comment by david50407** [comment]
Yes, IMO, the only way to break the routine is calling something like `halt`.

And the better that `halt` can follow up a response-relatived information like `redirect_to`, string or status code etc.

**Comment by eliasjpr** [comment]
@c910335 PR was opened addressing this issue https://github.com/amber-crystal/amber/pull/161 feel free to review.

@david50407 definitely agree with you, I honestly didn't want to use exceptions as a control flow. I have added notes why not use exceptions.

**Comment by eliasjpr** [comment]
Fixed with https://github.com/amber-crystal/amber/pull/168

**Comment by Xosmond** [comment]
Excuse me, i have:
`redirect_to(action: :index, status: 302)`

Do i have to add a halt after redirect_to method? Because I can't compile this code:

```
class CompanyController < ApplicationController
  @company : (Company | Nil) = nil
  before_action do
    only [:edit, :update] { set_company }
  end

  def edit
    render("edit.slang")
  end

  def update
    if @company.update company_params
      flash["success"] = "Compañia actualizada correctamente."
      redirect_to(action: :show, params: { "id" => @company.id.to_s } , status: 200)
    else
      flash["danger"] = "Verify the errors:"
      render("edit.slang")
    end
  end

  private def set_company
    @company = Company.find(params["id"])
    unless @company
      flash["warning"] = "Company not found"
      redirect_to(action: :index, status: 302)
    end
  end

  private def company_params
    params.to_h.select(["name"])
  end
end
```

The error says that @company variable is nil when I use update method, even when I call redirect_to when @company is nil to avoid execution of method

```
instantiating 'CompanyController#update()'
in src/controllers/company_controller.cr:37: undefined method 'update' for Nil (compile-time type is (Company | Nil))

    if @company.update company_params
```
