### ISSUE TITLE
Incorrect Amber Version

### ISSUE THREAD

**Issue by faustinoaq** [amber-crystal/amber#159]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem
    * Checked that your issue isn't already filed: https://github.com/Amber-Crystal/amber/issues
    * Checked that there is not already a Crystal Shard that provides the described functionality: http://crystalshards.xyz/

### Description

Incorrect version is shown.

### Steps to Reproduce

1. Create new Amber project
2. Run it

**Expected behavior:** Logs shows latest Amber version.

**Actual behavior:** Logs shows version `0.1.4`

**Reproduces how often:** 100%

### Versions

0.1.6

### Additional Information

![screenshot_20170802_114004](https://user-images.githubusercontent.com/3067335/28884410-54ebe3cc-7777-11e7-8b9f-c01392812274.png)

**Comment by faustinoaq** [comment]
Fixed!, just need to release a new Amber version (0.1.7) then ensure the `version.cr` is updated.

**Comment by elorest** [comment]
It works now. Just compile the latest version of amber_cmd.
