### ISSUE TITLE
Implementation of redirect_to fails when routes don't match format of #{controller}/#{action}

### ISSUE THREAD

**Issue by kellytaylor** [amber-crystal/amber#169]
Upon looking into adding flash to the **redirect_to** method I realized **redirect_to** is rather limited in quite a few cases. Most resourceful routes will fail. These are the three methods currently being used in `src/amber/controller/redirect.cr`:

```crystal
def redirect_to(location : String, *args)
  LocationRedirect.new(location, *args).redirect(response)
 end

# Redirects to the specified controller, action
def redirect_to(controller : Symbol, action : Symbol, *args)
  LocationRedirect.new("/#{controller}/#{action}", *args).redirect(response)
end

# Redirects within the same controller
def redirect_to(action : Symbol, *args)
  controller = self.class.to_s.chomp("Controller").downcase
  LocationRedirect.new("/#{controller}/#{action}", *args).redirect(response)
end
```

Let's say I had a route of 
```crystal
get "/topics", TopicsController, :index
```
If I were to pass in: 

```crystal
redirect_to(action: :index)
# It would redirect me to `/topics/index` and fail.

redirect_to(controller: :topics, action: :index)
# It would redirect me to `/topics/index` and fail. Same result. 
```

=======================================================================

## Suggestion:

- Give **redirect_to** the ability to determine the route when action or controller/action are passed in.
- Build the location more dynamically based on what is passed in.

I'm working on a solution now, let me know your thoughts. This solution would also change the way we are going to utilize flash and would be easy to integrate flash into this. However that can be two separate PR's if that's the preference. I'll let you know as soon as I have something.

**Comment by eliasjpr** [comment]
@kellytaylor thanks for bringing this up. I am in the middle of rewriting the `redirect_to` to make it more dynamic (I cannot agree with you more on this). Here is the current branch that I am working on https://github.com/amber-crystal/amber/tree/ep/add-flash-to-redirect Feel free collaborate I would like to hear your implementation thoughts as well.

**Comment by eliasjpr** [comment]
Fixed with https://github.com/amber-crystal/amber/pull/174
