### ISSUE TITLE
Not able to select redis session cache

### ISSUE THREAD

**Issue by josephcopenhaver** [amber-crystal/amber#176]
### Prerequisites

* [ x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem
    * Checked that your issue isn't already filed: https://github.com/Amber-Crystal/amber/issues
    * Checked that there is not already a Crystal Shard that provides the described functionality: http://crystalshards.xyz/

### Description
https://github.com/amber-crystal/amber/blob/70b01d5cfec941afa39c5568ea140586d20a4ef5/src/amber/router/session.cr#L13

This session case statement is attempting to use a string ( according to the docs at https://amber-crystal.gitbooks.io/amber/content/getting-started/Installation/configuration.html )
and comparing against code-refs.

As a result, I am unable to to use redis backed sessions. I actually discovered this when trying to add memcache backed sessions but I am unfortunately too new to write discrete tests. I was able to uncover the root issue by adding print statements just before the result values in the case statement. ( see https://github.com/josephcopenhaver/amber/tree/session_issue_test_case )

It could very well be that the documentation needs to change, but I think it would be best to not include class-paths in the app-config if we can help it.

### Steps to Reproduce

Add print statements link in https://github.com/josephcopenhaver/amber/tree/session_issue_test_case
Build a quick sample application and try to reconfigure it to use a different session cache type.

**Expected behavior:**

The documented method for altering cache type should work.

**Actual behavior:**

The documented method for altering cache type does not work, always getting
```
using signed_cookie cache
```
prints, even if I reconfigure for redis use

**Reproduces how often:**
100%

### Versions

Amber CMD (ambercr.io) - v0.1.21

### Additional Information

app.session[:store] = :redis
app.session[:store] = "redis"

```
  app.session = {
    :key     => "name.session",
    # :redis store available
    :store   => :redis,
    # 0, will make the session last as long as the browser is open, upon closing, session will be terminated
    :expires => 120,
    :secret  => "secret",
    # when store equals to :redis, must specify redis url
    :redis_url => "redis://localhost:6379",
  }
```

methods for changing the store type do not work

**Comment by eliasjpr** [comment]
@josephcopenhaver not sure Im following here, I am able to set redis as a session store, we have a  test against this as  well see https://github.com/amber-crystal/amber/blob/70b01d5cfec941afa39c5568ea140586d20a4ef5/spec/amber/router/session_spec.cr#L19

**Comment by josephcopenhaver** [comment]
Looks like I made an error somewhere. I ran the tests and they all pass, and I cannot repeat the issue I was having.

Thanks for being patient, still learning.
