### ISSUE TITLE
Extend  the default request object with additional methods

### ISSUE THREAD

**Issue by eliasjpr** [amber-crystal/amber#180]
The request object contains a lot of useful information about the request coming in from the client. To get a full list of the available methods, refer to the Crystal API Documentation https://crystal-lang.org/api/0.23.0/HTTP/Request.html

Crystal Request object is missing some useful methods and we should make them available to Amber.

- **format** to determine The content type requested by the client. (json, xml, html etc)
- **get?, post?, patch?, put?, delete?, head?** Returns true if the HTTP method is GET/POST/PATCH/PUT/DELETE/HEAD.
- **port** The port number (integer) used for the request.
- **url** The entire URL used for the request.
- **remote_ip** The IP address of the client.

**Comment by drujensen** [comment]
I don't think we should extend this in Amber. I think we should contribute these features to the standard library in Crystal.

**Comment by elorest** [comment]
Perhaps we should do both.

**Comment by eliasjpr** [comment]
As I was working on this today I thought of the same, this should be included in core Lib

**Comment by drujensen** [comment]
There is a PR for `remote_ip` and `peer_addr` in the standard core that has been their for quite a while:

https://github.com/crystal-lang/crystal/pull/1722

**Comment by eliasjpr** [comment]
Solved with #184
