### ISSUE TITLE
Add Rate Limiting

### ISSUE THREAD

**Issue by azah** [amber-crystal/amber#181]
How would this be best implemented?

**Comment by eliasjpr** [comment]
We required that all issues open none core member follow the issue  template. Please update this issue with all the details required, otherwise we would have to close this item. Amber Issue Template https://github.com/amber-crystal/amber/blob/master/.github/issue_template.md

**Comment by drujensen** [comment]
@azah to answer the question, you can either add nginx in front of amber

https://www.nginx.com/blog/rate-limiting-nginx/

or you can create a pipeline middleware similar to rack throttle:

https://github.com/dryruby/rack-throttle

btw, we have a gitter channel which is probably better suited for question like this.

https://gitter.im/Amber-Crystal/Lobby

**Comment by azah** [comment]
Ah I see, thanks!
