### ISSUE TITLE
undefined method 'configure' for Amber::Server:Class

### ISSUE THREAD

**Issue by igneus** [amber-crystal/amber#222]
### Description

Application generated by `amber n` doesn't compile.

### Steps to Reproduce

```
$ amber new -d sqlite first-amber-web
...
$ cd first-amber-web
$ crystal deps
...
$ amber watch
🤖  Your SentryBot is vigilant. beep-boop...
🤖  watching file: ./src/first-amber-web.cr
🤖  watching file: ./src/controllers/application_controller.cr
🤖  watching file: ./src/controllers/home_controller.cr
🤖  watching file: ./src/controllers/static_controller.cr
🤖  watching file: ./config/routes.cr
🤖  watching file: ./config/application.cr
🤖  watching file: ./src/views/layouts/application.slang
🤖  watching file: ./src/views/layouts/_nav.slang
🤖  watching file: ./src/views/home/index.slang
🤖  compiling first-amber-web...
Error in src/first-amber-web.cr:2: while requiring "../config/*"

require "../config/*"
^

in config/application.cr:3: undefined method 'configure' for Amber::Server:Class

Amber::Server.configure do |setting|
              ^~~~~~~~~


🤖  Compile time errors detected. SentryBot shutting down...
```

**Expected behavior:** The application compiles and runs
**Actual behavior:** Compilation fails

**Reproduces how often:** 100%

### Versions

```
$ amber --version
Amber CMD (ambercr.io) - v0.2.1
$ crystal --version
Crystal 0.23.1 [e2a1389] (2017-07-13) LLVM 3.8.1
```

on Linux, distribution Debian Stretch

**Comment by igneus** [comment]
Update: I saw https://github.com/amber-crystal/amber/commit/b43713f80f58865d7878bd570740c4b1d2bac8e0 ,
changed `Amber::Server.configure` "back" to `Amber::Server.instance.config`
and `Amber::Server.start` to `Amber::Server.instance.run`
and now the application compiles and runs.

**Comment by eliasjpr** [comment]
Please update to amber 0.2.2 since configure is reflected in those changes. 
See release https://github.com/amber-crystal/amber/releases/tag/v0.2.2
To update `brew upgrade amber-crystal/amber/amber`

**Comment by drujensen** [comment]
@igneus can we close this ticket?

**Comment by igneus** [comment]
Updated, project generated by `amber new` compiles. Thanks.

**Comment by roquie** [comment]
After updates crystal-lang and amber I'm too gets this error:

```
roquie@roquies-MacBook-Pro:~/google_drive/experiments/crystal/centurion$ crystal -v
Crystal 0.24.1 (2017-12-26)

LLVM: 5.0.1
Default target: x86_64-apple-macosx
roquie@roquies-MacBook-Pro:~/google_drive/experiments/crystal/centurion$ amber -v
Amber CLI (amberframework.org) - v0.6.1
roquie@roquies-MacBook-Pro:~/google_drive/experiments/crystal/centurion$
```

Any updates does not help me.

**Comment by roquie** [comment]
Heh, I find the solution. I installed Amber using crystal-lang 0.23.1 version and then only update the crystal-lang. What be fix this problem, I'm just uninstall Amber and re-install it using crystal-lang 0.24.1. Thats all!
