### ISSUE TITLE
Mailers

### ISSUE THREAD

**Issue by elorest** [Amber-Crystal/amber#53]
>As a Developer I want to deliver a mail message, by rendering one or more templates.

**Acceptance Criteria:**

- [ ] Send and receive email within the framework.
- [ ] Generate and edit an Mailer class and mailer view.
- [ ] Configure Action Mailer for my environment.
- [ ] Be able to test your Action Mailer classes.

**Comment by eliasjpr** [comment]
This was moved to its own repo
