### ISSUE TITLE
Accessing Cookies in Controller

### ISSUE THREAD

**Issue by elorest** [Amber-Crystal/amber#58]
Your application can store small amounts of data on the client - called cookies - that will be persisted across requests and even sessions.

**Comment by elorest** [comment]
This is currently implemented.

**Comment by eliasjpr** [comment]
PR https://github.com/Amber-Crystal/amber/pull/102

**Comment by eliasjpr** [comment]
Fixed with https://github.com/Amber-Crystal/amber/pull/114
