### ISSUE TITLE
Routes Resources

### ISSUE THREAD

**Issue by elorest** [Amber-Crystal/amber#66]
The router supports other macros besides those for HTTP verbs like get, post, and put. The most important among them is resources, which expands out to eight clauses of the match/3 function.

GET     /users           UserController :index
GET     /users/:id/edit  UserController :edit
GET     /users/new       UserController :new
GET     /users/:id       UserController :show
POST    /users           UserController :create
PATCH   /users/:id       UserController :update
PUT     /users/:id       UserController :update
DELETE  /users/:id       UserController :delete

**Comment by eliasjpr** [comment]
Resolved with 

https://github.com/Amber-Crystal/amber/pull/36
https://github.com/Amber-Crystal/amber/pull/37
https://github.com/Amber-Crystal/amber/pull/40
https://github.com/Amber-Crystal/amber/pull/75
