### ISSUE TITLE
Route Scopes

### ISSUE THREAD

**Issue by elorest** [Amber-Crystal/amber#67]
Scopes are a way to group routes under a common path prefix and scoped set of plug middleware. We might want to do this for admin functionality, APIs, and especially for versioned APIs. Let's say we have user generated reviews on a site, and that those reviews first need to be approved by an admin. The semantics of these resources are quite different, and they might not share the same controller. Scopes enable us to segregate these routes.

**Comment by eliasjpr** [comment]
Resolved with 

https://github.com/Amber-Crystal/amber/pull/43
https://github.com/Amber-Crystal/amber/pull/40
https://github.com/Amber-Crystal/amber/pull/35
