### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by elorest** [Amber-Crystal/amber#69]
Pipes Is a series composable transformations thru out the connection lifecycle. We interact with pipes at every step of the connection lifecycle, and the core Amber components like Endpoints, Routers, and Controllers are all just Pipes internally. The basic idea of a Pipe is to unify the concept of a "connection" that we operate on. This differs from other HTTP middleware layers such as Rack, where the request and response are separated in the middleware stack.

**Comment by eliasjpr** [comment]
Resolved with 
https://github.com/Amber-Crystal/amber/pull/16
https://github.com/Amber-Crystal/amber/pull/17
https://github.com/Amber-Crystal/amber/pull/35
https://github.com/Amber-Crystal/amber/pull/36
https://github.com/Amber-Crystal/amber/pull/40
https://github.com/Amber-Crystal/amber/pull/43
https://github.com/Amber-Crystal/amber/pull/45
https://github.com/Amber-Crystal/amber/pull/48
https://github.com/Amber-Crystal/amber/pull/74
