### ISSUE TITLE
Controller Filters

### ISSUE THREAD

**Issue by elorest** [Amber-Crystal/amber#71]
Controller Filters are reusable modules that lives within the controller layer and the sole purpose is to validate and transform request/response data. Filters are useful for validating controller action, transforming controller actions the difference between a Pipe and a Filter is that a filter acts on a specific context such as the request, response, session, headers etc., while a Pipe action on the connection lifecycle.

**Comment by eliasjpr** [comment]
Resolved with 
https://github.com/Amber-Crystal/amber/pull/30
https://github.com/Amber-Crystal/amber/pull/41
