### ISSUE TITLE
Controller Actions Params Validation

### ISSUE THREAD

**Issue by elorest** [Amber-Crystal/amber#72]
* Parameters are taken from the context env and passed as an argument to #call. They are similar to a Ruby Hash, but they offer an expanded set of features.
    * Look into 
        * https://github.com/dry-rb/dry-logic/blob/master/lib/dry/logic/predicates.rb
        * https://github.com/neovintage/accord

* Whitelisting and Validations
* params do
      required(:name).filled(:str?)
      required(:email).filled(:str?, format?: /@/).confirmation
      required(:password).filled(:str?).confirmation
      required(:terms_of_service).filled(:bool?)
      required(:age).filled(:int?, included_in?: 18..99)
      optional(:avatar).filled(size?: 1..(MEGABYTE * 3))
    end

**Comment by eliasjpr** [comment]
Resolved with https://github.com/Amber-Crystal/amber/pull/21
